# Generated by Django 6.0.1 on 2026-01-21 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RG inválido', regex='^[0-9A-Za-z\\.\\-]+$')])),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('cargo', models.CharField(choices=[('AGENTE DE POLÍCIA JUDICIÁRIA', 'Agente de Polícia Judiciária'), ('PAPILOSCOPISTA', 'Papiloscopista'), ('ASSESSOR', 'Assessor'), ('ADMINISTRATIVO', 'Administrativo'), ('DELEGADO DE POLICIA', 'Delegado de Policia')], default='AGENTE DE POLÍCIA JUDICIÁRIA', max_length=100)),
                ('telefone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (DD) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')])),
            ],
        ),
    ]
