# Generated by Django 6.0.1 on 2026-01-19 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida (formatos aceitos: AAA1234 ou AAA1A23)', regex='^([A-Z]{3}[0-9]{4}|[A-Z]{3}[0-9][A-Z][0-9]{2})$')])),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Viajante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rg', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='RG inválido', regex='^[0-9A-Za-z\\.\\-]+$')])),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('cargo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
