# Generated by Django 6.0.1 on 2026-01-19 18:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajante',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='RG inválido', regex='^[0-9A-Za-z\\.\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Telefone inválido. Use o formato (DD) XXXXX-XXXX', regex='^\\(\\d{2}\\)\\s\\d{4,5}-\\d{4}$')]),
        ),
    ]
