# Generated by Django 6.0.1 on 2026-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('modelo', models.CharField(max_length=20)),
                ('combustivel', models.CharField(choices=[('ETANOL', 'Etanol'), ('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel')])),
            ],
        ),
        migrations.AlterField(
            model_name='viajante',
            name='cargo',
            field=models.CharField(choices=[('AGENTE DE POLÍCIA JUDICIÁRIA', 'Agente de Polícia Judiciária'), ('PAPILOSCOPISTA', 'Papiloscopista'), ('ASSESSOR', 'Assessor'), ('ADMINISTRATIVO', 'Administrativo'), ('DELEGADO DE POLICIA', 'Delegado de Policia')], default='AGENTE DE POLÍCIA JUDICIÁRIA'),
        ),
    ]
