# Generated by Django 6.0.1 on 2026-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_alter_viajante_rg_alter_viajante_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajante',
            name='cargo',
            field=models.CharField(choices=[('AGENTE DE POLÍCIA JUDICIÁRIA', 'Agente de Polícia Judiciária'), ('PAPILOSCOPISTA', 'Papiloscopista'), ('ASSESSOR', 'Assessor'), ('ADMINISTRATIVO', 'Administrativo')], default='AGENTE DE POLÍCIA JUDICIÁRIA', max_length=100),
        ),
    ]
