# Generated by Django 6.0.1 on 2026-01-21 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0002_veiculo_alter_viajante_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('ETANOL', 'Etanol'), ('GASOLINA', 'Gasolina'), ('DIESEL', 'Diesel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Placa inválida. Use o formato AAA1234 ou AAA1A23', regex='^([A-Z]{3}[0-9]{4}|[A-Z]{3}[0-9][A-Z][0-9]{2})$')]),
        ),
    ]
