# Generated by Django 6.0.1 on 2026-01-22 12:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_alter_veiculo_combustivel_alter_veiculo_placa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oficio', models.CharField(max_length=50, unique=True)),
                ('protocolo', models.CharField(blank=True, max_length=50, null=True)),
                ('sede', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('servidor', models.CharField(max_length=100)),
                ('data_saida', models.DateField()),
                ('data_chegada', models.DateField()),
                ('valor_diaria', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('veiculo', models.CharField(blank=True, max_length=50, null=True)),
                ('motorista', models.CharField(blank=True, max_length=100, null=True)),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aprovado', 'Aprovado'), ('concluido', 'Concluído')], default='rascunho', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
