# Generated by Django 6.0.1 on 2026-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0003_alter_viajante_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='viajante',
            name='cargo_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='cargo',
            field=models.CharField(choices=[('AGENTE DE POLÍCIA JUDICIÁRIA', 'Agente de Polícia Judiciária'), ('PAPILOSCOPISTA', 'Papiloscopista'), ('ASSESSOR', 'Assessor'), ('ADMINISTRATIVO', 'Administrativo'), ('OUTRAS', 'Outras')], default='AGENTE DE POLÍCIA JUDICIÁRIA', max_length=100),
        ),
    ]
