# Generated by Django 6.0.1 on 2026-01-22 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_oficio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficio',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='oficio',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='oficio',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_motorista', to='viagens.viajante'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='oficio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='protocolo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='servidor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficios_servidor', to='viagens.viajante'),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('concluido', 'Concluído')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viagens.veiculo'),
        ),
    ]
