# Generated by Django 6.0.1 on 2026-01-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0004_viajante_cargo_custom_alter_viajante_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='viajante',
            name='cargo_custom',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='combustivel',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('ETANOL', 'Etanol'), ('DIESEL', 'Diesel')], default='ETANOL', max_length=10),
        ),
        migrations.AlterField(
            model_name='viajante',
            name='cargo',
            field=models.CharField(choices=[('AGENTE DE POLÍCIA JUDICIÁRIA', 'Agente de Polícia Judiciária'), ('PAPILOSCOPISTA', 'Papiloscopista'), ('ASSESSOR', 'Assessor'), ('ADMINISTRATIVO', 'Administrativo')], default='AGENTE DE POLÍCIA JUDICIÁRIA', max_length=100),
        ),
    ]
