# Generated by Django 6.0.1 on 2026-01-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0005_remove_oficio_atualizado_em_remove_oficio_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajante',
            name='cargo',
            field=models.CharField(choices=[('Agente de Polícia Judiciária', 'Agente de Polícia Judiciária'), ('Papiloscopista', 'Papiloscopista'), ('Assessor', 'Assessor'), ('Administrativo', 'Administrativo'), ('Delegado de Policia', 'Delegado de Policia')], default='AGENTE DE POLÍCIA JUDICIÁRIA'),
        ),
    ]
