# Generated by Django 6.0.1 on 2026-01-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viagens', '0007_cidade_remove_oficio_destino_remove_oficio_sede_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficio',
            name='motorista_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro_ida',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='oficio',
            name='roteiro_volta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='oficio',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oficios_motorista', to='viagens.viajante'),
        ),
    ]
